# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
highlighter: pygments

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Leo Martel
author_email: leo@lpm.io
title: Lpm.io
# url: http://localhost:4000     # Development
url: http://lpm.io               # Production
github_url: http://github.com/lmartel
linkedin_url: http://www.linkedin.com/in/leopmartel/

collections:
  projects:
    output: true
    permalink: /projects/:title/

resume_url: https://dl.dropboxusercontent.com/u/84750930/leo_martel_resume.pdf
resume_date: September 28, 2014
